[tool.poetry]
name = "test-py-opencv"
version = "0.1.0"
description = "Test OpenCV Project"
authors = ["Your Name"]
readme = "README.md"
packages = [{ include = "test_py_opencv", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
numpy = "==2.4.2"
opencv-python = "==4.13.0.92"
moviepy = "==1.0.3"

[tool.poetry.scripts]
demo = "test_py_opencv.demo:main"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"